Document: ace
Title: Debian ace Manual
Author: <insert document author here>
Abstract: This manual describes what ace is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ace/ace.sgml.gz

Format: postscript
Files: /usr/share/doc/ace/ace.ps.gz

Format: text
Files: /usr/share/doc/ace/ace.text.gz

Format: HTML
Index: /usr/share/doc/ace/html/index.html
Files: /usr/share/doc/ace/html/*.html
